apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-blog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: api
          image: docker.io/padminibuddaraju/simple-blog-api
          ports:
            - containerPort: 3000
          resources:
            limits:
                memory: "128Mi"
                cpu: "500m"  